### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by as754770178** [ming71/mmdetection-annotated#11]
看到博客中有car.json，但我在git工程中没有找到这个数据。

**Comment by as754770178** [comment]
我找到`mmdetection-annotated/annotation/dataset_example`中数据，在进行数据读取时，报错
```
Traceback (most recent call last):
  File "/home/zgz/code/rcnn/mmdetection/tools/train.py", line 111, in <module>
    main()
  File "/home/zgz/code/rcnn/mmdetection/tools/train.py", line 89, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/builder.py", line 39, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/utils/registry.py", line 76, in build_from_cfg
    return obj_cls(**args)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/custom.py", line 63, in __init__
    self.img_infos = self.load_annotations(ann_file)
  File "/home/zgz/code/rcnn/mmdetection/mmdet/datasets/coco.py", line 28, in load_annotations
    self.cat_ids = self.coco.getCatIds()
  File "/home/zgz/code/rcnn/faster-rcnn.pytorch/lib/pycocotools/coco.py", line 178, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'
```

**Comment by ming71** [comment]
car.json是自己标注的，用Labeme

**Comment by ming71** [comment]
后来改成train.json了
