### ISSUE TITLE
训练模块出错

### ISSUE THREAD

**Issue by suranliunian** [ming71/mmdetection-annotated#8]
**运行
~/mmdetection$ python tools/train.py configs/cascade_rcnn_x101_32x4d_fpn_1x.py --validate
时**

2019-07-25 10:13:28,296 - INFO - Distributed training: False
2019-07-25 10:13:30,073 - INFO - load model from: open-mmlab://resnext101_32x4d
**Downloading: "https://s3.ap-northeast-2.amazonaws.com/open-mmlab/pretrain/third_party/resnext101_32x4d-a5af3160.pth" to /home/yaping/.cache/torch/checkpoints/resnext101_32x4d-a5af3160.pth**
Traceback (most recent call last):
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  ......(省略)
  File "/home/yaping/anaconda3/envs/mmd/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

显示下载resnext101_32x4d-a5af3160.pth，但是超时，是不是从国外网站下载不下来resnext101_32x4d-a5af3160.pth这个文件啊？ 请问有相关的文件么？谢谢啦！

**Comment by ming71** [comment]
你可以检查一下是不是有权值文件，没有权重是无法跑val的

**Comment by ming71** [comment]
提示的这个是预训练模型，在加载的时候会自动下载，如果不下载可以点击链接手动下，然后放到指定的文件夹就行

**Comment by suranliunian** [comment]
嗯呢，非常感谢！！！
